#filename:.travis.yml
dist: xential
sudo: false
notifications:
  email: false
env:
  global:
  - REPO=gfwlist2dnsmasq
script:
- mkdir -p $TRAVIS_BUILD_DIR/output
- ./gfwlist2dnsmasq.sh -l -o ./output/gfwlist_domain.txt
- ./gfwlist2dnsmasq.sh -o ./output/dnsmasq_gfwlist.conf
- ./gfwlist2dnsmasq.sh -s gfwlist -o ./output/dnsmasq_gfwlist_ipset.conf
- DATE_TIME=$(date "+%Y-%m-%d %H:%M:%S")
- cd /tmp/
- git clone https://${GIT_USER}:${TOKEN}@github.com/${GIT_USER}/${REPO}.git --branch gh-pages --single-branch gh-pages > /dev/null 2>&1 || exit 1
- cd gh-pages || exit 1
- git config user.name "cokebar"
- git config user.email "cokebar@cokebar.info"
- cp $TRAVIS_BUILD_DIR/output/* .
- git add -A
- git commit -a -m "Configuration Files Generated on [$DATE_TIME]"
- git push -fq origin gh-pages > /dev/null 2>&1 || exit 1
- echo -e "Uploaded files to gh-pages\n"
